---
kind: pipeline
name: ubuntu18test

platform:
  os: linux
  arch: amd64

# instance:
#   include:
#     - drone.fdiopoc.net
#     - 5346a318.ngrok.io

steps:
- name: checkstyle
  image: index.docker.io/snergster/vpp-ubuntu18
  commands:
    - git fetch --tags || true
    - build-root/scripts/checkstyle.sh
    - make test-checkstyle
  when:
    event:
      -push
- name: vppbuildtest
  image: index.docker.io/snergster/vpp-ubuntu18
  privileged: true
  commands:
    - sudo mount -o remount /dev/shm -o size=1024M || true
    - grep search /etc/resolv.conf || true
    - git fetch --tags || true
    - make UNATTENDED=yes verify
  when:
    event:
    - push
