kind: pipeline
name: ubuntu

steps:
- name: vppbuild
  image: index.docker.io/snergster/vpp-ubuntu18
  commands:
  - ls -l
  - git pull || true
  - make UNATTENDED=yes install-dep
  - make pkg-deb

when:
  event:
  - push

---
kind: pipeline
name: centos

steps:
- name: vppbuild
  image: index.docker.io/snergster/vpp-centos
  commands:
  - ls
  - git pull || true
  - make UNATTENDED=yes verify

when:
  event:
  - push

---
kind: pipeline
name: ubuntuarm

platform:
  os: linux
  arch: arm64

steps:
- name: vppbuild
  image: index.docker.io/snergster/ubuntu18arm
  commands:
  - ls -l
  - git pull || true
  - make UNATTENDED=yes verify

when:
  event:
  - push
  instance:
    include:
      - drone.fdiopoc.net
      - *.ngrok.io
