---
kind: pipeline
name: ubuntu18test

platform:
  os: linux
  arch: amd64

services:
  docker:
    image: index.docker.io/snergster/vpp-ubuntu18
    privileged: true
# instance:
#   include:
#     - drone.fdiopoc.net
#     - 5346a318.ngrok.io

steps:
- name: vppbuildtest
  image: docker
  commands:
    - df -h
    - sudo mount -o remount /dev/shm -o size=1024M || true
    - df -h
    - git pull || true
    - make UNATTENDED=yes verify
  when:
    event:
    - push
