kind: pipeline
name: default

steps:
- name: vppbuild
  image: index.docker.io/snergster/vpp-ubuntu18
  shm_size: '1gb'
  commands:
  - ls
  - git pull || true
  - make UNATTENDED=yes verify

when:
  event:
  - push
