---
kind: pipeline
name: ubuntuarm

# platform:
#   os: linux
#   arch: arm64
# instance:
#   include:
#     - drone.fdiopoc.net
#     - 5346a318.ngrok.io

steps:
- name: vppbuildarm
  image: index.docker.io/snergster/ubuntu18arm
  commands:
  - git pull || true
  - make UNATTENDED=yes verify
  when:
    event:
    - push
