kind: pipeline
name: ubuntu

steps:
- name: vppbuild
  image: index.docker.io/snergster/vpp-ubuntu18
  commands:
  - ls -l
  - git pull || true
  - make UNATTENDED=yes install-dep
  - make pkg-deb
  when:
    event:
    - push
    instance:
      exclude:
        - drone.fdiopoc.net
        - 5346a318.ngrok.io
---
kind: pipeline
name: centos

steps:
- name: vppbuildcentos
  image: index.docker.io/snergster/vpp-centos
  commands:
  - git pull || true
  - make UNATTENDED=yes verify
  when:
    event:
    - push
    instance:
      exclude:
        - drone.fdiopoc.net
        - 5346a318.ngrok.io

