---
kind: pipeline
name: ubuntu18test

platform:
  os: linux
  arch: amd64

# instance:
#   include:
#     - drone.fdiopoc.net
#     - 5346a318.ngrok.io

steps:
- name: checkstyle
  image: index.docker.io/snergster/vpp-ubuntu18
  commands:
    - git fetch --tags || true
    - build-root/scripts/checkstyle.sh
    - make test-checkstyle
  when:
    event:
      -push
      -pull_request
- name: vppbuildtest
  image: index.docker.io/snergster/vpp-ubuntu18
  privileged: true
  commands:
    - sudo mount -o remount /dev/shm -o size=1024M || true
    - apt-get install -y vpp-ext-deps || true
    - grep search /etc/resolv.conf || true
    - git fetch --tags || true
    - make UNATTENDED=yes verify
  when:
    event:
    - pull_request
    - push
- name: vpppush
  environment:
    REPO:
      from_secret: repo
    token:
      from_secret: token
    STREAM: master
    pclogin: snergster
  image: index.docker.io/snergster/vpp-ubuntu18
  privileged: true
  commands:
    - echo 'push only'
    - rm /root/.packagecloud
    - echo $key > /root/.packagecloud
    - chmod 755 /usr/local/bin/pc_push || true
    - /usr/local/bin/pc_push || true
  when:
    event:
    - push
