kind: pipeline
name: default

steps:
- name: vppbuild
  image: index.docker.io/snergster/vpp-ubuntu18
  privileged: true
  commands:
  - ls
  - sudo mount -o remount /dev/shm -o size=1024M || true
  - git pull || true
  - make UNATTENDED=yes verify

when:
  event:
  - push
