version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build vpp using Docker
          command: |
            docker build . -f .circleci/docker/verify/Dockerfile.xenial

