version: 2
jobs:
  ubuntu16:
    docker:
      - image: snergster/vpp-ubuntu16
    steps:
      - run:
          command: |
            sudo apt-get update -qq
            sudo apt-get install moreutils -y
      - run:
          name: Cache Prep
          command: |
            sudo mkdir -p /var/ccache
            #sudo chown -R circleci:circleci ~/vpp/build-root/.ccache
      - restore_cache:
          keys:
            #- ccache-v1-{{ .BRANCH }}-{{epoch}}
            - ccache-v1-master-{{epoch}}
            - ccache-v1-{{epoch}}
            - ccache-v1
            - ccache-
      - run:
          name: ccache setup
          command: |
            ccache --version
            ccache --show-stats
            ccache --zero-stats
            ccache --max-size=2G
      - checkout
      - run: curl -s https://packagecloud.io/install/repositories/fdio/master/script.deb.sh | sudo bash
      - run: unset CCACHE_READONLY
      - run: make UNATTENDED=yes verify
      - run:
          name: ccache stats
          command: |
            export CCACHE_DIR=/var/ccache
            ccache --show-stats
      - save_cache:
#          key: ccache-v1-{{.BRANCH}}-{{epoch}}
          key: ccache-v1-master-{{epoch}}
          paths:
            - /var/ccache
  centos7:
    docker:
      - image: snergster/vpp-centos
    steps:
      - checkout
      - run: curl -s https://packagecloud.io/install/repositories/fdio/master/script.rpm.sh | sudo bash
      - run: yum -y install vpp-ext-deps || true
      - run: make UNATTENDED=yes verify

  ubuntu18:
    docker:
      - image: snergster/vpp-ubuntu18
    steps:
      - checkout
      - run: make UNATTENDED=yes install-dep
      - run: make pkg-deb
workflows:
  version: 2
  build_and_test:
    jobs:
      - ubuntu16
      - centos7
      - ubuntu18
