version: 2
jobs:
  ubuntu16:
    docker:
      - image: snergster/vpp-ubuntu16
    steps:
      - checkout
      - run: make UNATTENDED=yes verify
  centos7:
    docker:
      - image: snergster/vpp-centos
    steps:
      - checkout
      - run: make UNATTENDED=yes verify
workflows:
  version: 2
  build_and_test:
    jobs:
      - ubuntu16
      - centos7
