version: 2
jobs:
  ubuntu16:
    docker:
      - image: snergster/vpp-ubuntu16
    steps:
      - run:
          command: |
            sudo apt-get update -qq
            sudo apt-get install moreutils -y
      - run:
          name: Cache Prep
          command: |
            sudo mkdir -p /var/ccache
      - restore_cache:
          keys:
            - ccache-v1-{{ .Environment.CIRCLE_JOB }}-{{ .BRANCH }}
      - run:
          name: ccache setup
          command: |
            ccache --version
            ccache --show-stats
            ccache --zero-stats
            ccache --max-size=2G
      - checkout
      - run: curl -s https://packagecloud.io/install/repositories/fdio/master/script.deb.sh | sudo bash
      - run: 
          name: ccache check
          command: |
            printenv
            unset CCACHE_READONLY
            whoami
            printenv
            export CCACHE_READONLY=false;make UNATTENDED=yes verify
      - run:
          name: ccache stats
          command: |
            export CCACHE_DIR=/var/ccache
            ccache --show-stats
      - save_cache:
          key: ccache-v1-{{ .Environment.CIRCLE_JOB }}-{{ .BRANCH }}
          paths:
            - /var/ccache
  centos7:
    docker:
      - image: snergster/vpp-centos
    steps:
      - restore_cache:
          keys:
            - ccache-v1-{{ .Environment.CIRCLE_JOB }}-{{ .BRANCH }}
      - run:
          name: ccache setup
          command: |
            ccache --version
            ccache --show-stats
            ccache --zero-stats
            ccache --max-size=2G
      - checkout
      - run: curl -s https://packagecloud.io/install/repositories/fdio/master/script.rpm.sh | sudo bash
      - run: yum -y install vpp-ext-deps || true
      - run:
          name: verify with cache
          command: |
            printenv
            unset CCACHE_READONLY
            whoami
            printenv
            export CCACHE_READONLY=false;make UNATTENDED=yes verify
      - run:
          name: ccache stats
          command: |
            export CCACHE_DIR=/var/ccache
            ccache --show-stats
      - save_cache:
          key: ccache-v1-{{ .Environment.CIRCLE_JOB }}-{{ .BRANCH }}
          paths:
            - /var/ccache

  ubuntu18:
    docker:
      - image: snergster/vpp-ubuntu18
    steps:
      - restore_cache:
          keys:
            - ccache-v1-{{ .Environment.CIRCLE_JOB }}-{{ .BRANCH }}
      - run:
          name: ccache setup
          command: |
            ccache --version
            ccache --show-stats
            ccache --zero-stats
            ccache --max-size=2G
      - checkout
      - run:
          name: printenv
          command: |
            printenv
            unset CCACHE_READONLY
            whoami
            printenv
      - run: 
          name: installdep
          command: |
            make UNATTENDED=yes install-dep
      - run: export CCACHE_READONLY=false;make pkg-deb
      - run:
          name: ccache stats
          command: |
            export CCACHE_DIR=/var/ccache
            ccache --show-stats
      - save_cache:
          key: ccache-v1-{{ .Environment.CIRCLE_JOB }}-{{ .BRANCH }}
          paths:
            - /var/ccache

workflows:
  version: 2
  build_and_test:
    jobs:
      - ubuntu16
      - centos7
      - ubuntu18
